apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kafka-0
spec:
  capacity:
    storage: 10Gi 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/kafka/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.215.0.10 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kafka-1
spec:
  capacity:
    storage: 10Gi 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/kafka/data 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.215.0.11 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kafka-2
spec:
  capacity:
    storage: 10Gi 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/kafka/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.215.0.23
